### ISSUE TITLE
Publish to Hex

### ISSUE THREAD

**Issue by leland-rasmussen** [emqx/jq#51]
Hi team 👋 Is it possible to publish this library to Hex? It could be done by adding an extra step to the build CI pipeline, similar to how brod does it: https://github.com/kafka4beam/brod/blob/master/.github/workflows/build.yml

What do you think?

**Comment by zmstone** [comment]
Hi @leland-rasmussen 

Not possible at the moment, because this repo uses git submodule for C code dependency.

**Comment by leland-rasmussen** [comment]
Ok, thank you for the reply!
